"""HTTP-based extraction tools.

Phase 1 foundation.

These tools are deterministic execution components. They have no
knowledge of the LLM or agent reasoning.

The agent chooses the tool, but storage location is controlled by the
application rather than allowing the model to write arbitrary paths.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Dict

import requests

from core.exceptions import ToolExecutionError
from storage.paths import raw_path


DEFAULT_TIMEOUT_SECONDS = 60


def http_download(
    url: str,
    save_path: str,
    timeout: int = DEFAULT_TIMEOUT_SECONDS,
) -> Dict[str, Any]:
    """Download a URL and save the artifact locally.

    ``save_path`` is currently retained as part of the Phase 1 tool
    interface so existing tests and the agent contract remain compatible.

    The supplied path is resolved relative to the current project
    environment. Later phases can replace this with a deterministic
    source-specific path generated by ``storage.paths``.

    Args:
        url:
            URL to download.

        save_path:
            Local destination path.

        timeout:
            HTTP request timeout in seconds.

    Returns:
        Structured download result.

    Raises:
        ToolExecutionError:
            If the request fails or the server returns a non-success
            HTTP status.
    """

    try:
        response = requests.get(
            url,
            timeout=timeout,
            allow_redirects=True,
        )

        response.raise_for_status()

    except requests.exceptions.Timeout as exc:
        raise ToolExecutionError(
            message=(
                f"Request to {url} timed out "
                f"after {timeout}s"
            ),
            error_type="Timeout",
            recoverable=True,
        ) from exc

    except requests.exceptions.HTTPError as exc:
        status_code = (
            exc.response.status_code
            if exc.response is not None
            else None
        )

        raise ToolExecutionError(
            message=(
                f"HTTP error downloading {url}: {exc}"
            ),
            error_type="HTTPError",
            recoverable=(
                status_code is not None
                and status_code >= 500
            ),
        ) from exc

    except requests.exceptions.RequestException as exc:
        raise ToolExecutionError(
            message=(
                f"Request error downloading {url}: {exc}"
            ),
            error_type="RequestException",
            recoverable=True,
        ) from exc

    path = Path(save_path)

    path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    path.write_bytes(
        response.content
    )

    return {
        "success": True,
        "url": url,
        "file_path": str(path),
        "bytes": len(response.content),
        "content_type": response.headers.get(
            "content-type",
            "unknown",
        ),
    }
